### ISSUE TITLE
Psych library differences from JRuby

### ISSUE THREAD

**Issue by headius** [ruby/psych#102]
I just did an update of psych .rb files for JRuby, and the following diff is the only thing I had to reject:

``` diff
@@ -96,7 +98,7 @@ module Psych
   VERSION         = '1.3.4'

   # The version of libyaml Psych is using
-  LIBYAML_VERSION = Psych.libyaml_version.join '.' unless RUBY_ENGINE == 'jruby'
+  LIBYAML_VERSION = Psych.libyaml_version.join '.'

   class Exception < RuntimeError
   end
```

Ideally this change or something like it would get into Psych upstream so I can just copy freely in the future.

**Comment by kares** [comment]
this is no longer relevant - should be closed
