### ISSUE TITLE
Exception dumping depends on MRI-specific internals

### ISSUE THREAD

**Issue by headius** [ruby/psych#103]
The following method depends on MRI-specific internal variables in Exception objects, and as a result it doesn't marshal exceptions properly in JRuby:

``` ruby
      def visit_Exception o
        tag = ['!ruby/exception', o.class.name].join ':'

        @emitter.start_mapping nil, tag, false, Nodes::Mapping::BLOCK

        {
          'message'   => private_iv_get(o, 'mesg'),
          'backtrace' => private_iv_get(o, 'backtrace'),
        }.each do |k,v|
          next unless v
          @emitter.scalar k, nil, nil, true, false, Nodes::Scalar::ANY
          accept v
        end

        dump_ivars o

        @emitter.end_mapping
      end
```

I'll see if I can come up with a patch.

**Comment by headius** [comment]
The times have changed and now only the `mesg` hidden instance variable is being accessed. Unfortunately there's still no alternative way to get the raw message from an exception, since the `message` method will return the class `to_s` result if `mesg` is not set.

A patch to remove the use of `mesg` is below, but it fails one test because the result of `message` is always a string, and the type doesn't match what was originally in `mesg`:

```diff
diff --git a/lib/psych/visitors/yaml_tree.rb b/lib/psych/visitors/yaml_tree.rb
index 79ca129..986c57b 100644
--- a/lib/psych/visitors/yaml_tree.rb
+++ b/lib/psych/visitors/yaml_tree.rb
@@ -181,7 +181,7 @@ module Psych
       end
 
       def visit_Exception o
-        dump_exception o, private_iv_get(o, 'mesg')
+        dump_exception o, o.message.to_s
       end
 
       def visit_NameError o
```

It would seem to me an ok limitation that YAML can only serialize and restore the string version of `message`, since the internal type of `mesg` should typically never be seen by users.

The failure is below:

```
  1) Failure:
Psych::TestException#test_convert [/Users/headius/projects/psych/test/psych/test_exception.rb:159]:
No visible difference in the Psych::TestException::Wups#inspect output.
You should look at the implementation of #== on Psych::TestException::Wups or its members.
#<Psych::TestException::Wups: Psych::TestException::Wups>
```

I'm fine with this issue being closed, since there's no zero-cost resolution and CRuby has never exposed the raw `mesg` contents.

**Comment by headius** [comment]
FWIW if the diff is accepted, the `private_iv_get` logic from the extension can be removed.

**Comment by tenderlove** [comment]
> It would seem to me an ok limitation that YAML can only serialize and restore the string version of message, since the internal type of mesg should typically never be seen by users.

I agree.

I think removing `private_iv_get` would be great. Can you fix the test and lets merge this?

**Comment by Fryguy** [comment]
Blast from the past 😊

**Comment by headius** [comment]
@tenderlove Finally circling back to this since I need #457 released too. Will fix test and do a PR.

**Comment by headius** [comment]
🎉

**Comment by eregon** [comment]
Looks like a great change, thanks!
