### ISSUE TITLE
Can't read from GzipReader: undefined method `external_encoding'

### ISSUE THREAD

**Issue by ghostganz** [ruby/psych#105]
I was doing this successfully with Ruby 1.9.2 and Syck:

``` ruby
require 'zlib'
require 'yaml'
data = YAML.load(Zlib::GzipReader.new(open('foo.yml.gz'))
```

but with Psych it fails like this:

``` ruby
NoMethodError: undefined method `external_encoding' for #<Zlib::GzipReader:0x007fa36303ffa8>
```

so it looks like it's assuming things about the input stream that aren't always true.

**Comment by akostadinov** [comment]
any update? why not allow reading yaml from a stream? This is most natural and memory efficient. After all it can read from a file stream, why not from a zstream?

**Comment by IronSavior** [comment]
:+1: Same issue here

**Comment by josephholsten** [comment]
You want:

 ```ruby
require 'zlib'
require 'psych'

data = Psych.load_stream(Zlib::GzipReader.open('foo.yml.gz'))
```

**Comment by ghostganz** [comment]
I still feel the original code _should_ work -- but maybe it already does, since 4.5 years have passed. But Psych.load_stream is fine too, so I'm simply closing this. :)
