### ISSUE TITLE
 Unknown alias: -624431998 (Psych::BadAlias)

### ISSUE THREAD

**Issue by bacancy-anand** [ruby/psych#135]
Hi I am developing application with Cucumber Testing. I have used VCR to record request and response. I am facing error sometime when I run cucumber test. Here is the stack trace:
`
 Unknown alias: -624431998 (Psych::BadAlias)
      /home/anand/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:246:in`block in visit_Psych_Nodes_Alias'
      /home/anand/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:246:in `fetch'
      /home/anand/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:246:in`visit_Psych_Nodes_Alias'
      /home/anand/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych/visitors/visitor.rb:15:in `visit'
      /home/anand/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych/visitors/visitor.rb:5:in`accept'
      /home/anand/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:20:in `accept'
      /home/anand/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:283:in`block in revive'
      /home/anand/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:283:in `map'
      /home/anand/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:283:in`revive'
      /home/anand/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:219:in `visit_Psych_Nodes_Mapping'
`
But When I delete Cassatt and rerun the test feature, it works fine. 

I want to know that why this error is coming and what should I do to remove this error permanently. Any suggestion would be appreciated. Thank you.

**Comment by reneedv** [comment]
I saw this issue with a database.yml file as well -> we had this line:
```` ruby
cucumber:
  <<: *test
````
once I took it out it worked.

**Comment by Dwija09** [comment]
Can anyone help me, i m facing this problem while using ceedling test:all command

Traceback (most recent call last):
        38: from D:/Ruby27-x64/bin/ceedling:23:in `<main>'
        37: from D:/Ruby27-x64/bin/ceedling:23:in `load'
        36: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ceedling-0.31.1/bin/ceedling:278:in `<top (required)>'
        35: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych.rb:670:in `load_file'
        34: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych.rb:670:in `open'
        33: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych.rb:671:in `block in load_file'
        32: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych.rb:370:in `load'
        31: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych.rb:335:in `safe_load'
        30: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:35:in `accept'
        29: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:6:in `accept'
        28: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:30:in `visit'
        27: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
        26: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:35:in `accept'
        25: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:6:in `accept'
        24: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:30:in `visit'
        23: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        22: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
        21: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
        20: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:343:in `each'
        19: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        18: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:35:in `accept'
        17: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:6:in `accept'
        16: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:30:in `visit'
        15: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        14: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
        13: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
        12: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:343:in `each'
        11: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        10: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:35:in `accept'
         9: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:6:in `accept'
         8: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:30:in `visit'
         7: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
         6: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:338:in `register_empty'
         5: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:338:in `each'
         4: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:338:in `block in register_empty'
         3: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:35:in `accept'
         2: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:6:in `accept'
         1: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:30:in `visit'
D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: common_defines (Psych::BadAlias)###

**Comment by Dwija09** [comment]
Can anyone help me out in solving this problem

C:\demo>ceedling test:all


Test 'test_light.c'
-------------------
Running test_light.out...
rake aborted!
Errno::EACCES: Permission denied - build\test\out\test_light.out 2>&1
C:/Ruby26-x64/bin/ceedling:23:in `load'
C:/Ruby26-x64/bin/ceedling:23:in `<main>'
Tasks: TOP => build/test/results/test_light.pass
(See full trace by running task with --trace)
