### ISSUE TITLE
Double quotes

### ISSUE THREAD

**Issue by Exoth** [ruby/psych#157]
Pull request #106 makes this:

```
Psych.dump("@123'abc")
--- "@123'abc"
```

But now it's again back to single quotes because of this commit: 69a1aea11b5687a500d0901e7513691766ce80d4

It would be great if double quotes are used in case a single quote is inside the dumped string and there are no double quotes inside.

**Comment by wteuber** [comment]
@tenderlove I found the same a very similar issue when there is a key involved. Especially when working with i18n's YAML files this is confusing people.
```
Psych.dump("key: @123'abc")
--- 'key: @123''abc'
```
Do you agree that's worth fixing as well?
Thanks a lot in advanced.
