### ISSUE TITLE
Unable to parse Ruby constants from YAML file

### ISSUE THREAD

**Issue by buckolas** [ruby/psych#165]
Here is an example YAML file, called 'sample.yml':

development:
   verify: !ruby/module OpenSSL::SSL::VERIFY_NONE

Parsing this YAML file in the development.rb file, as shown here:

``` ruby
verify = YAML.load_file("#{Rails.root}/config/sample.yml")[Rails.env][:verify]
```

I get the following error:
TypeError: OpenSSL::SSL::VERIFY_NONE does not refer to class/module
from [Ruby Base]/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:312:in 'path2class'
.....

I have tried using !ruby/fixnum and other options in the YAML file, with no success. Any ideas on how to get the constant to parse properly?

**Comment by etdsoft** [comment]
I'm wondering what's the right approach here...

```ruby
require 'openssl'
require 'psych'

p Psych.load(File.read('config.yml'))
```
Running it:
```
$ bundle exec ruby test.rb
./psych-2.2.2/lib/psych/class_loader.rb:54:in `path2class': OpenSSL::SSL::VERIFY_PEER does not refer to class/module (TypeError)
```

The source YAML:
```
encryption:
  method:        !ruby/symbol simple_tls
  tls_options:
    verify_mode: !ruby/module OpenSSL::SSL::VERIFY_PEER
```

If I change `!ruby/module` for `!ruby/constant` no errors, but the constant isn't parsed, a string is:

```
$ bundle exec ruby test.rb
{"encryption"=>{"method"=>:simple_tls, "tls_options"=>{"verify_mode"=>"OpenSSL::SSL::VERIFY_PEER"}}}
```
