### ISSUE TITLE
psych won't install on Ruby 2.0.0-p353, libyaml-0.1.4, on OSX 10.8.5

### ISSUE THREAD

**Issue by cjheath** [ruby/psych#182]
All versions freshly updated, but "gem install psych" says:
ERROR:  Error installing psych:
    invalid gem: package is corrupt, exception while verifying: undefined method `path2class' for #Psych::ClassLoader:0x000001013b6b98 (NoMethodError) in /Users/<user>/.rvm/gems/ruby-2.0.0-p353/cache/psych-2.0.2.gem

**Comment by TakahikoKawasaki** [comment]
The immediate cause is that `psych.so` is not located at the proper location. In my case, the workaround was as follows:

    cp /usr/local/share/ruby/gems/2.0/gems/psych-2.0.13/lib/psych.so \
       /usr/share/ruby/vendor_ruby/2.0/

The packaging process of either Psych or Ruby might be wrong.

See http://stackoverflow.com/a/30118186/1174054 for details.
