### ISSUE TITLE
dump() with anchors and arrays produces output that can't be properly parsed with ruby 1.8.7

### ISSUE THREAD

**Issue by eric** [ruby/psych#184]
The yaml [output by ruby 1.9.3](https://eval.in/100273):

``` yaml
---
:a: &75700340
- 10.0.0.1
- 10.0.0.2
:b: *75700340
:c: *75700340
```

cannot be properly [parsed by ruby 1.8.7](https://eval.in/100270):

``` ruby
{:b=>nil, :c=>nil, :a=>["10.0.0.1", "10.0.0.2"]}
```

The yaml from 1.8.7 looks like:

``` yaml
--- 
:a: &id001 
  - 10.0.0.1
  - 10.0.0.2
:b: *id001
:c: *id001
```

...which has spaces before the `-` for the array elements.

Here's some samples of the outputs and how they are parsed:

https://eval.in/100270+100271

**Comment by hsbt** [comment]
Ruby 1.8/1.9 is EOL now.
