### ISSUE TITLE
Psych should expose start_mark and end_mark to handlers

### ISSUE THREAD

**Issue by Sharpie** [ruby/psych#197]
Writing low-level Psych-based parsers is difficult without access to the `start_mark` and `end_mark` data attached to `libyaml` events. Took a shot at hacking this in, but my Ruby-fu at the C level just isn't strong enough yet.

**Comment by asterite** [comment]
I'm also needing this and I could work and send a PR for this, though I don't know how it would integrate with `Psych::Handler`'s interface.

The main issue is that the current `Psych::Parser#mark` gives you the location after the event has happened, which is not very useful. To get the correct/useful event location you need to use `start_mark` and `end_mark`, which are not exposed by Psych.

**Comment by jemc** [comment]
For context about the "what are you building" question - this is desired for printing compiler-style error messages on invalid data (that has a valid YAML syntax, but data is rejected by the applications). Here, "compiler-style error messages" means showing the line and column where the invalid data was found alongside the error message. The purpose is to create a better user experience for an application that "compiles" from YAML files.
