### ISSUE TITLE
JRUBY: ERROR:  While executing gem ... (Errno::ENOENT) 

### ISSUE THREAD

**Issue by rinkevichjm** [ruby/psych#260]
JRUBY_HOME=C:\Users\first.last\workspace\TestBed\vendor
GEM_PATH=GEM_HOME=C:\Users\/first.last\workspace\TestBed\vendor\vendor\gem_home
C:\Program Files\Java\jre\bin\java -jar jruby-complete-9.0.4.0.jar  -S gem install psych -v 2.0.16
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - C:/Users/first.last/workspace/TestBed/vendor/vendor/gem_home/gems/psych-2.0.16-java/deps.lst

gem list command claims it is installed

**Comment by rinkevichjm** [comment]
before the error:
Fetching: ruby-maven-libs-3.3.3.gem (100%)
Successfully installed ruby-maven-libs-3.3.3
Fetching: ruby-maven-3.3.8.gem (100%)
Successfully installed ruby-maven-3.3.8
Files\Java\jre"" was unexpected at this time.

**Comment by kares** [comment]
does not seem like this was really a psych issue at all. its also (old) jruby-complete specific. 
if anyone land here report against JRuby using an up to date version.

**Comment by hsbt** [comment]
There is lack of feedback over 5 years.
