### ISSUE TITLE
invalid value for Float(): "7.e-002"

### ISSUE THREAD

**Issue by joerixaop** [ruby/psych#279]
This exception is thrown for the following code:

```
{"test" => "7.e-002"}.to_yaml
```

tested with both the psych version bundled with ruby 2.2.3 (psych 2.0.8) and the latest version of psych (2.0.17)

**Comment by tenderlove** [comment]
This was fixed in d5c9b2d4aee89483b79dc4930b79dec7031ef936 and released in v2.1.1
