### ISSUE TITLE
dyld: Symbol not found: _rb_ary_new4

### ISSUE THREAD

**Issue by hktalent** [ruby/psych#289]
$cd ~
$ gem list --local
dyld: lazy symbol binding failed: Symbol not found: _rb_ary_new4
Referenced from: /Users/xiatian/.rvm/gems/ruby-2.3.1/gems/psych-2.1.1/lib/psych.bundle
Expected in: flat namespace

dyld: Symbol not found: _rb_ary_new4
Referenced from: /Users/xiatian/.rvm/gems/ruby-2.3.1/gems/psych-2.1.1/lib/psych.bundle
Expected in: flat namespace

but 
cd /Users/xiatian/safe/metasploit-framework
so
$ gem list --local
is ok
why?
thank you

**Comment by hsbt** [comment]
Did you upgrade ruby from old version like 2.2 or 2.1? It was built by old version of ruby.

Please invoke `gem pristine psych` or re-install your ruby.
