### ISSUE TITLE
It appears that there's no -java version published for 2.1.1

### ISSUE THREAD

**Issue by brianseeders** [ruby/psych#290]
See title

**Comment by headius** [comment]
Confirmed. Unfortunately I do not have permission to push psych gems. @tenderlove?

**Comment by tenderlove** [comment]
Derp, sorry.  I'll ship it and give you push access

**Comment by hsbt** [comment]
@headius I added psych owner grant to you

**Comment by headius** [comment]
I have pushed 2.1.1-java. Thanks, @hsbt!
