### ISSUE TITLE
Parser exception for valid anchor name

### ISSUE THREAD

**Issue by frntn** [ruby/psych#291]
Gitlab uses Psych to parse `.gitlab-ci.yml` file

But when trying to load this valid YAML... 

``` yaml
YAML.safe_load <<EOS
.ci:common: &ci:common
  only:
    - tags

lint:status:
  script: echo this valid yaml fails at gitlab.com/ci/lint test
  <<: *ci:common
EOS
```

...the parser actually fails

```
=> Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 2 column 7
from /home/grzesiek/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych.rb:377:in `parse'
```

It seems the parser doesn't accept the colon char (`:`) in anchors while it should : http://www.yaml.org/spec/1.2/spec.html#id2785586

If you want more details, my discussion with Gitlab dev team is available here :
=> https://gitlab.com/gitlab-org/gitlab-ce/issues/19547#note_16115131

**Comment by tenderlove** [comment]
libyaml is a YAML 1.1 parser, not a YAML 1.2 parser.  This is probably not valid in YAML 1.1.
