### ISSUE TITLE
Can't load files with characters in the supplementary plane

### ISSUE THREAD

**Issue by cataphract** [ruby/psych#293]
Loading YAML fails if they have a character in the supplementary plane:

<pre>
jruby-9.1.5.0 :002 > require 'yaml'; YAML.load('೬')
 => "೬" 
jruby-9.1.5.0 :003 > require 'yaml'; YAML.load('1🎁')
Psych::SyntaxError: (<unknown>): 'reader' unacceptable character ' at line 0 column 0
    from org/jruby/ext/psych/PsychParser.java:231:in `parse'
    from /home/glopes/.rvm/rubies/jruby-9.1.5.0/lib/ruby/stdlib/psych.rb:376:in `parse_stream'
    from /home/glopes/.rvm/rubies/jruby-9.1.5.0/lib/ruby/stdlib/psych.rb:324:in `parse'
    from /home/glopes/.rvm/rubies/jruby-9.1.5.0/lib/ruby/stdlib/psych.rb:251:in `load'
    from (irb):3:in `<eval>'
    from org/jruby/RubyKernel.java:995:in `eval'
    from org/jruby/RubyKernel.java:1296:in `loop'
    from org/jruby/RubyKernel.java:1115:in `catch'
    from org/jruby/RubyKernel.java:1115:in `catch'
    from /home/glopes/.rvm/rubies/jruby-9.1.5.0/bin/irb:13:in `<main>'
</pre>

Confusingly, it says the error is at line 0 column 0.

**Comment by tenderlove** [comment]
Looks like you're using JRuby.  I think this is a problem with SnakeYAML since it seems to work fine with MRI:

```
irb(main):001:0> require 'psych'
=> true
irb(main):002:0> require 'yaml'; YAML.load('1🎁')
=> "1🎁"
irb(main):003:0>
```

/cc @headius

**Comment by headius** [comment]
This is fixed in snakeyaml but not yet released. I requested a release here: https://bitbucket.org/asomov/snakeyaml/issues/323/is-there-any-reason-to-not-support#comment-34466839
