### ISSUE TITLE
Missing JRuby gem for 2.2.0

### ISSUE THREAD

**Issue by headius** [ruby/psych#295]
Every time you release Psych without releasing the JRuby version, you break our users trying to install it. Today we had another case of this...a user could no longer update his gems because 2.2.0 was released only for MRI.

Please always release the JRuby gem, or make sure someone who can release it is available.

**Comment by headius** [comment]
Ping @hsbt, since it seems he did this release.

**Comment by headius** [comment]
Pushed 2.2.0-java to RG.org.

**Comment by hsbt** [comment]
@headius Should I push psych-java gem every release without `ext/java` changes?

**Comment by headius** [comment]
@hsbt Yes, you must or you break psych installing for JRuby users. RubyGems does not look for a previous release with platform support. If the C ext is released and the JRuby ext is not, RubyGems will always try to install the C ext.

FWIW the Java ext is almost line-for-line a port of the C ext. It will not be hard to keep it up to date.

**Comment by hsbt** [comment]
> RubyGems does not look for a previous release with platform support.

That make sense. I will release psych simultaneously.

Thanks your advice.

**Comment by headius** [comment]
Related: #297.
