### ISSUE TITLE
Switching to Bundler breaks JRuby packaging

### ISSUE THREAD

**Issue by tenderlove** [ruby/psych#297]
On Psych v2.0.16, I can run `rake package` using JRuby and I'll get a gem file that contains the compiled `.jar` file:

```
[aaron@TC psych ((v2.0.16))]$ jruby -v
jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.77-b03 on 1.8.0_77-b03 +jit [darwin-x86_64]
[aaron@TC psych ((v2.0.16))]$ gem install hoe rake-compiler ruby-maven
Fetching: hoe-3.15.2.gem (100%)
Successfully installed hoe-3.15.2
Fetching: rake-compiler-1.0.2.gem (100%)
Successfully installed rake-compiler-1.0.2
Fetching: ruby-maven-libs-3.3.9.gem (100%)
Successfully installed ruby-maven-libs-3.3.9
Fetching: ruby-maven-3.3.12.gem (100%)
Successfully installed ruby-maven-3.3.12
4 gems installed
[aaron@TC psych ((v2.0.16))]$ rake package

[snip lots of output]

WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: psych
  Version: 2.0.16
  File: psych-2.0.16-java.gem
mv psych-2.0.16-java.gem ..
cd -
[aaron@TC psych ((v2.0.16))]$ gem spec pkg/psych-2.0.16-java.gem | grep jar
  name: jar-dependencies
- lib/psych.jar
- lib/psych_jars.rb
- jar org.yaml:snakeyaml, 1.14
[aaron@TC psych ((v2.0.16))]$
```

It's *very* important that the `-java` gem contains the `.jar` file.  @hsbt is there a reason we switched to Bundler?  Using `hoe`, and the previous `Rakefile` allowed us to build the JRuby gem easily, and also prevents bugs like cf1264d636417bbd5ce51e1c284a452f0cf1f8ba.

I'm not clear how to fix the Rakefile so that the Bundler packaging system will work well with JRuby.  Can you try fixing it?  If it's too hard to fix, then I would like to revert the changes made to the Rakefile.

Thanks!

**Comment by headius** [comment]
`gem build` does appear to properly build the gem with the jar-dependencies stuff but there's nothing automated.

**Comment by headius** [comment]
See 146a637e2205b2b36a6fa83fc0c6f7ce0c74e123 for some hardcoded constants I had to do because `gem build` is inadequate.

**Comment by tenderlove** [comment]
@headius I think `gem build` will include *only* the jar dependencies, not `lib/psych.jar`.  I think this means that people who are using Psych on JRuby are requiring `lib/psych.jar` from older versions of Psych they have installed.  So if you try to use Psych 2.2.0, you'll end up requiring `lib/psych.jar` from 2.0.16 (or whatever other version you happen to have installed)

**Comment by hsbt** [comment]
> I'm not clear how to fix the Rakefile so that the Bundler packaging system will work well with JRuby. Can you try fixing it?

I use `rake compile` for building to java extension. It works fine. 

Note: current master is broken status for me.

```
ext/java/PsychParser.java:246: error: cannot find symbol
            RubyArray.newArray(runtime, runtime.newFixnum(_version.major()), runtime.newFixnum(_version.minor()));
                                                                                                       ^
  symbol:   method minor()
  location: variable _version of type Version
```

Packaging task of bundler is defacto standard in Ruby ecosystem now. I hope to moving forward to use it task.
