### ISSUE TITLE
Fedora 25 gem update fail

### ISSUE THREAD

**Issue by pathaugen** [ruby/psych#306]
Fedora 25 workstation clean install under Oracle VirtualBox latest version:
5.1.12 r112440 (Qt5.6.2)

Fedora 25 updated via:
> $ sudo dnf update kernel*
> $ uname -r
4.9.3-200.fc25.x86_64

Ruby Version:
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]

psych error occurs under this situation when running:
> sudo gem update

When it gets to psych, drops an error and refers to the log file:
/usr/local/lib64/gems/ruby/psych-2.2.2/mkmf.log

Contents of log file:
`"gcc -o conftest -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic -fPIC conftest.c  -L. -L/usr/lib64 -L. -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic  -m64   -lruby  -lpthread -ldl -lcrypt -lm   -lc"
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory`

This again is Fedora 25, and the link over to redhat is of concern. Causes a failure.

**Comment by tenderlove** [comment]
When you update or install a gem, it uses the same compiler flags that were used to compile Ruby.  Whatever Ruby installation you're using was compiled with `-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1`.  My best guess is that you either need to recompile your Ruby, or install the package that has that directly.  Maybe `redhat-hardened-cc1`?
