### ISSUE TITLE
Documentation needs to show how to catch all exceptions psych can throw

### ISSUE THREAD

**Issue by marko-avlijas** [ruby/psych#309]
I shouldn't be forced to google / ask on stackoverflow.

And this is not encouraging:
http://stackoverflow.com/questions/14676656/cant-rescue-yaml-load-exception

It seems you intentionally derived from some very hard to catch exception and only God knows how many different exceptions you are throwing.

**Comment by tenderlove** [comment]
Please don't make assumptions about my intentions.  Patches welcome.
