### ISSUE TITLE
 YAML.load do not work as expected

### ISSUE THREAD

**Issue by daixiang0** [ruby/psych#323]
```
irb(main):001:0> require 'yaml'
=> true
irb(main):002:0> YAML.load 'run_on_local_disk: yes'
=> {"run_on_local_disk"=>true}

```
I want to get this val as yes, do i need to add some option to get my expect result?

**Comment by daixiang0** [comment]
safe_load also fail:
```
irb(main):001:0> a='run_on_local_disk: yes'
=> "run_on_local_disk: yes"
irb(main):002:0> require 'yaml'
=> true
irb(main):003:0> YAML.safe_load a
=> {"run_on_local_disk"=>true}

```

**Comment by wteuber** [comment]
@daixiang0 This is intended behaviour, please see https://github.com/ruby/psych/blob/aec5469ef4a784e185e4e18ea542f3b5ef0f602f/test/psych/test_boolean.rb#L9

**Comment by tenderlove** [comment]
As @wteuber says, [this is expected behavior](http://yaml.org/type/bool.html).  If you need the string `yes`, then format your yaml like this:

```
irb(main):013:0> YAML.load 'run_on_local_disk: "yes"'
=> {"run_on_local_disk"=>"yes"}
irb(main):014:0>
```

Hope that helps!

**Comment by tjoyal** [comment]
Late to the party but I've been wondering why 

https://github.com/ruby/psych/blame/aec5469ef4a784e185e4e18ea542f3b5ef0f602f/test/psych/test_boolean.rb#L22-L23

I couldn't find a decision or bug related to it.
