### ISSUE TITLE
syntax error prevents `gem update`

### ISSUE THREAD

**Issue by syslogic** [ruby/psych#344]
https://github.com/ruby/psych/blob/6333cf8cc365b644fbffd8b122f2e720f5654e77/lib/psych/scalar_scanner.rb#L146

    [martin@redhat ~]$ gem update
    /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require': 
    /usr/local/share/gems/gems/psych-3.0.0/lib/psych/scalar_scanner.rb:146: syntax error, unexpected tIDENTIFIER, expecting ')' (SyntaxError)
    klass.new(yy, m, dd, hh, mm, ss+us/(1_000_000r))
                                                    ^
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/psych-3.0.0/lib/psych/nodes/node.rb:4:in `<top (required)>'
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/psych-3.0.0/lib/psych/nodes.rb:2:in `<top (required)>'
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/psych-3.0.0/lib/psych.rb:14:in `<top (required)>'
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/ruby/site_ruby/rubygems.rb:686:in `load_yaml'
        from /usr/local/share/ruby/site_ruby/rubygems/config_file.rb:340:in `load_file'
        from /usr/local/share/ruby/site_ruby/rubygems/config_file.rb:202:in `initialize'
        from /usr/local/share/ruby/site_ruby/rubygems/gem_runner.rb:75:in `new'
        from /usr/local/share/ruby/site_ruby/rubygems/gem_runner.rb:75:in `do_configuration'
        from /usr/local/share/ruby/site_ruby/rubygems/gem_runner.rb:40:in `run'
        from /usr/bin/gem:21:in `<main>'

when I change that line to `klass.new(yy, m, dd, hh, mm)` it updates, including `psych-3.0.1.gem.`

**Comment by hsbt** [comment]
What's your ruby version?

**Comment by syslogic** [comment]
Arch        : x86_64
    Version     : 2.0.0.648
    Release     : 30.el7
    
    From repo   : rhel-7-desktop-rpms

**Comment by hsbt** [comment]
psych-3 only support >= Ruby 2.2.2. Please update your ruby version.

**Comment by stomar** [comment]
@syslogic See #343.
