### ISSUE TITLE
Unable to install psych in R 3.4.3 and mac OS Sierra

### ISSUE THREAD

**Issue by diazdc** [ruby/psych#348]
Installing package into ‘/Users/dude/Library/R/3.4/library’
(as ‘lib’ is unspecified)
Error: 9:15: unexpected symbol
8:          else if(Sys.getenv("NVIMR_TMPDIR") != "")
9:   x           options
                 ^
Execution halted
Warning in install.packages :
  installation of package ‘/Users/dude/Downloads/psych_1.7.8.tar.gz’ had non-zero exit status

sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.16

**Comment by stomar** [comment]
This repository is for Ruby, not R.
