### ISSUE TITLE
Can't install the latest version on Windows!

### ISSUE THREAD

**Issue by aadrian** [ruby/psych#353]
The latest stable version of Ruby for Windows:
`ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]`

Does not seem to work with the latest version of `psych` :( .

Trying to install it with `gem install psych` will display the following error on Windows:
```
ERROR:  Error installing psych:
        The last version of psych (>= 0) to support your Ruby & RubyGems was 3.0.2. Try installing it with `gem install
psych -v 3.0.2`
        psych requires Ruby version < 2.5, >= 2.2. The current ruby version is 2.5.0.
```

Thank you.

**Comment by MSP-Greg** [comment]
@aadrian

```
PS C:\> gem list psych

*** LOCAL GEMS ***

psych (default: 3.0.2)

PS C:\> ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
```

So, the latest version is included in 2.5.1.  The RubyGems message is not exactly clear, but I don't recall issues when I was upgrading other gems.  Please close if you don't have any more questions...

**Comment by MSP-Greg** [comment]
@maxnorris

The gem itself will install on 2.5 and probably trunk, but the Windows pre-compiled gem is only built for 2.2 thru 2.4.  Updating that has been overlooked...

If you have MSYS2 installed, it should install with:

```
gem update psych --platform=ruby
```

It installed on my system that way.

For the maintainers - I do have PowerShell code available that constructs the gem along with testing, so every Appveyor job builds a gem, which can be helpful for testing.  It has been used with Ruby 2.0 thru trunk, both 32 & 64 bit.

**Comment by maxnorris** [comment]
Ah ha, I missed that.  Forcing the compile worked perfectly, thanks,
