### ISSUE TITLE
documentation lacking

### ISSUE THREAD

**Issue by celesteking** [ruby/psych#361]
There's practically zero documentation for this library.

For example, I'm looking for serialization routines and possibly the tree traverser that would allow me to craft custom result tree. 

This link (the official doc) is useless https://ruby-doc.org/stdlib-2.5.1/libdoc/yaml/rdoc/YAML.html
Even searching on Internet returns very much limited info:  https://www.google.com/search?q=ruby+yaml+serialization+encode_with

https://github.com/ruby/psych/blob/master/lib/psych/visitors/to_ruby.rb  contains 3 comment lines out of 400.

What are the plans on writing API documentation for the lib?

**Comment by yuki24** [comment]
While it is true that there is room for improvement in the doc, none of the Ruby committers maintains https://ruby-doc.org and thus it's not an official doc. Also, we always try to make our best effort to maintain the project, it is nowhere close to enterprise-level customer support as this is an open-source project driven by community effort.

Any contribution is greatly appreciated.

**Comment by estani** [comment]
I think also this is very lacking...

I found in yaml_tree an option for `line_width` which I have no idea how to set while dumping the yaml.
I think there are alternative gems to do things this library might already be capable of, but there's just too little information (not even load_file is described here!).
As Usual the best place for documentation is in code self, second best is in repo, so here in the REadme would be enough. That way over pull request we can help extending/correcting it.

**Comment by hsbt** [comment]
Welcome to your contribution.
