### ISSUE TITLE
Problem | (<unknown>): did not find expected key while parsing a block mapping at line 13 column 7

### ISSUE THREAD

**Issue by Souljwsh** [ruby/psych#367]
I don't get it. Where is the wrong situation?
-=-=--
(<unknown>): did not find expected key while parsing a block mapping at line 13 column 7
Here is the config (homes.yml): http://www.mediafire.com/file/ztb94h3aqfv8qoh/homes.yml/file
And here is the photo of the YAML Validator: http://prntscr.com/keobmu
*if you want to help me with that, you can go on the site*
http://www.yamllint.com/

**Comment by sorryeh** [comment]
Please post the config inline using markdown code fencing.
reference: https://guides.github.com/features/mastering-markdown/

For any photo's, add them inline with the drag and drop feature of Github :)

Nothing against you, but I don't follow links to third parties nor will I download content.

Cheers! It will be a pleasure to help you settle this

**Comment by GutoLusilo** [comment]
I'm having trouble with the same error.

This is the error:
```
YAML syntax error occurred while parsing / {...} /config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): did not find expected key while parsing a block mapping at line 7 column 3
```

And this is `database.yml`:
```ruby
default:
  adapter: postgresql
  encoding: unicode
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
development:
  adapter: postgresql
  database: chamada_development
  encoding: unicode
  password: "<%= ENV['CHAMADA_DATABASE_PASSWORD'] %>"
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
  username: chamada
production:
  adapter: postgresql
  database: chamada_production
  encoding: unicode
  password: "<%= ENV['CHAMADA_DATABASE_PASSWORD'] %>"
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
  username: chamada
test:
  adapter: postgresql
  database: chamada_test
  encoding: unicode
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
```

**Comment by jdsoteldo** [comment]
did you solve it? have the same problem?
