### ISSUE TITLE
Can't update rubocop to 0.65 on Ruby 2.6 because psych windows binaries require Ruby <2.6

### ISSUE THREAD

**Issue by aried3r** [ruby/psych#385]
When trying to update rubocop from 0.64 to 0.65 `bundle update` failed, because psych x64-mingw64 forces Ruby to be < 2.6.
https://rubygems.org/gems/psych/versions/3.1.0-x64-mingw32
https://rubygems.org/gems/psych/versions/3.1.0-x86-mingw32
compare to
https://rubygems.org/gems/psych/versions/3.1.0

    rubocop (~> 0.65) was resolved to 0.65.0, which depends on
      psych (>= 3.1.0) was resolved to 3.1.0, which depends on
        ruby (< 2.6) x64-mingw32

I solved this in the meanwhile by explicitly specifying the `psych` gem in my Gemfile using 
```Ruby
gem 'psych', platform: :ruby
```

**Comment by hsbt** [comment]
Thanks, It's strange behavior. I will investigate it.

**Comment by ashmaroli** [comment]
All versions cut for `mingw` platform have a constraint on the Ruby version. For examples,
- [psych-3.1.0-x86](https://rubygems.org/gems/psych/versions/3.1.0-x86-mingw32)
- [psych-3.1.0-x64](https://rubygems.org/gems/psych/versions/3.1.0-x64-mingw32)
- [psych-3.0.3-x86](https://rubygems.org/gems/psych/versions/3.0.3-x86-mingw32)
- [psych-3.0.3-x64](https://rubygems.org/gems/psych/versions/3.0.3-x64-mingw32)
- [psych-3.0.2-x86](https://rubygems.org/gems/psych/versions/3.0.2-x86-mingw32)
- [psych-3.0.2-x64](https://rubygems.org/gems/psych/versions/3.0.2-x64-mingw32)

**Comment by hsbt** [comment]
Maybe, It's a limitation of `rake-compiler-dock`

**Comment by ashmaroli** [comment]
@hsbt Probably because `pysch-3.1` was released before Ruby2.6 was officially released.
Can we expect a `psych-3.1.1` cut with the latest `rake-compiler-dock` anytime soon..?

**Comment by hsbt** [comment]
Unfortunately, We discontinue to release mingw binaries now. I'll close this.
