### ISSUE TITLE
ArgumentError when execute `ridk version` on non English version Windows 

### ISSUE THREAD

**Issue by tan-wei** [ruby/psych#420]
Feel strange when I execute `ridk version`, `psych` throw the execption.
```console
ridk version
Traceback (most recent call last):
        11: from C:/Ruby25/bin/ridk.cmd:39:in `<main>'
        10: from C:/Ruby25/lib/ruby/site_ruby/2.5.0/ruby_installer/runtime/ridk.rb:24:in `run!'
         9: from C:/Ruby25/lib/ruby/site_ruby/2.5.0/ruby_installer/runtime/ridk.rb:168:in `print_version'
         8: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/psych-3.1.0-x86-mingw32/lib/psych/core_ext.rb:13:in `to_yaml'
         7: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/psych-3.1.0-x86-mingw32/lib/psych.rb:513:in `dump'
         6: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/psych-3.1.0-x86-mingw32/lib/psych/visitors/yaml_tree.rb:118:in `push'
         5: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/psych-3.1.0-x86-mingw32/lib/psych/visitors/yaml_tree.rb:136:in `accept'
         4: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/psych-3.1.0-x86-mingw32/lib/psych/visitors/yaml_tree.rb:358:in `visit_Hash'
         3: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/psych-3.1.0-x86-mingw32/lib/psych/visitors/yaml_tree.rb:358:in `each'
         2: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/psych-3.1.0-x86-mingw32/lib/psych/visitors/yaml_tree.rb:360:in `block in visit_Hash'
         1: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/psych-3.1.0-x86-mingw32/lib/psych/visitors/yaml_tree.rb:136:in `accept'
C:/Ruby25/lib/ruby/gems/2.5.0/gems/psych-3.1.0-x86-mingw32/lib/psych/visitors/yaml_tree.rb:298:in `visit_String': invalid byte sequence in UTF-8 (ArgumentError)
```

**Comment by MSP-Greg** [comment]
@tan-wei

I've got a standard EN-US Windows 10 system, and I can't repo this using Ruby 2.5.7.

The line that is calling psych is `puts h.to_yaml`, and h is hashes nested two deep.  Maybe for debugging, add something like `puts '', h.inspect, ''` before ridk.rb:168 and see if any characters seem incorrect?

I suspect this is an encoding issue, whether it's Psych, or Ruby, or RubyInstaller2, I don't know.

Finally, non-Windows Ruby dev's may have never heard of `ridk`, maybe add 'Windows' to the issue subject line?

**Comment by tan-wei** [comment]
@MSP-Greg Thanks for your reply.
Yes, I think the issue can only repo in Windows 10 which is not EN-US version. So I think it may be the issue of the encoding. After I update Ruby from 2.5.4 to 2.6.4, the issue still exists in my ENV.

And I'll modify the title then. Many thanks!

**Comment by MSP-Greg** [comment]
Thanks.  If you could try adding the 'inspect' line, it would be helpful to know what's causing the encoding issue.  It's kind of odd, as the paths shown in your first post are 'ASCII' compatible.

Regardless, you can close this issue if you wish, I don't think it's a psych issue...

**Comment by tan-wei** [comment]
After I add `pp h`, I find that it is the encoding issue. So I think the issue should be closed here.

PS: Information displayed:
```ruby
{"ruby"=>{"path"=>"C:/Ruby26", "version"=>"2.6.5", "platform"=>"i386-mingw32"},
 "ruby_installer"=>{"package_version"=>"2.6.5-1", "git_commit"=>"d3e0c65"},
 "msys2"=>{"path"=>"C:\\Ruby26\\msys32"},
 "cc"=>"i686-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 9.2.0",
 "sh"=>"GNU bash，版本 4.4.23(1)-release (i686-pc-msys)",
 "os"=>"Microsoft Windows [\xB0汾 10.0.18362.476]"}
```
