### ISSUE TITLE
Java Psych fails in ugly ways when SnakeYAML version is wrong

### ISSUE THREAD

**Issue by headius** [ruby/psych#428]
Originally reported via https://github.com/jruby/jruby/issues/6023

When the version of SnakeYAML loaded does not match the one required by JRuby's Psych extension, it produces a very arcane Java error:

```
% jruby -S bundle install
Ignoring bcrypt-ruby-3.0.0-java because its extensions are not built. Try: gem pristine bcrypt-ruby --version 3.0.0
Ignoring bindex-0.5.0 because its extensions are not built. Try: gem pristine bindex --version 0.5.0
Ignoring sassc-1.11.4 because its extensions are not built. Try: gem pristine sassc --version 1.11.4
/home/enebo/work/jruby/lib/ruby/stdlib/psych.rb:7: warning: already initialized constant SNAKEYAML_VERSION
/home/enebo/work/jruby/lib/ruby/stdlib/psych.rb:7: warning: already initialized constant ANY
/home/enebo/work/jruby/lib/ruby/stdlib/psych.rb:7: warning: already initialized constant UTF8
/home/enebo/work/jruby/lib/ruby/stdlib/psych.rb:7: warning: already initialized constant UTF16LE
/home/enebo/work/jruby/lib/ruby/stdlib/psych.rb:7: warning: already initialized constant UTF16BE
org/jruby/RubyKernel.java:984: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
LoadError: load error: psych -- java.lang.NoClassDefFoundError: Could not initialize class org.jruby.ext.psych.PsychEmitter
LoadError: load error: psych -- java.lang.NoClassDefFoundError: Could not initialize class org.jruby.ext.psych.PsychEmitter
```

This is caused by an API mismatch; SnakeYAML changed its "Mark" API in an incompatible way. If the old SnakeYAML loads first, loading of the Psych extension continues but eventually fails when it tries to call this API.

We should try to modify the JRuby version of Psych to fail earlier when SnakeYAML is not the expected version. I'll look into this a bit today.

**Comment by headius** [comment]
Sadly it does not appear there's a way to query SnakeYAML for its version. The best option might be for us to try to reflectively load the Mark method that changed and produce a hard error if it is not present.

**Comment by eregon** [comment]
This part of the warning is confusing and I think not applicable for JRuby:
```
org/jruby/RubyKernel.java:984: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
```

**Comment by headius** [comment]
@eregon Yeah good point, I'll see if I can also patch that to be more relevant.

**Comment by headius** [comment]
The libyaml warning comes from stdlib yaml.rb, so I'll have to patch it on the JRuby side.

**Comment by samtrapp42** [comment]
Where can I find snakeyaml 1.21?
I have rubygem 2.0

**Comment by headius** [comment]
@samtrapp42 The snakeyaml dependency should be installed at gem install time using the jar-dependencies library (specific to JRuby). jar-dependencies fetches requirements from the Maven repository.
