### ISSUE TITLE
Do not change $LOAD_PATH in psych.gemspec

### ISSUE THREAD

**Issue by mame** [ruby/psych#454]
@deivid-rodriguez @tenderlove 

The change for https://github.com/ruby/psych/pull/433, which has been merged into ruby/ruby, produces dozens of warnings during `make test-all` in ruby master.

http://rubyci.s3.amazonaws.com/ubuntu2004/ruby-master/log/20200608T123004Z.log.html.gz
```
[15092/20234]
TestRDocOptions#test_init_with_encoding/home/chkbuild/chkbuild/tmp/build/20200608T123004Z/ruby/ext/psych/lib/psych.rb:233: warning: already initialized constant Psych::LIBYAML_VERSION
/home/chkbuild/chkbuild/tmp/build/20200608T123004Z/ruby/.ext/common/psych.rb:233: warning: previous definition of LIBYAML_VERSION was here
/home/chkbuild/chkbuild/tmp/build/20200608T123004Z/ruby/ext/psych/lib/psych.rb:235: warning: already initialized constant Psych::NOT_GIVEN
/home/chkbuild/chkbuild/tmp/build/20200608T123004Z/ruby/.ext/common/psych.rb:235: warning: previous definition of NOT_GIVEN was here
/home/chkbuild/chkbuild/tmp/build/20200608T123004Z/ruby/ext/psych/lib/psych.rb:271: warning: method redefined; discarding old load
/home/chkbuild/chkbuild/tmp/build/20200608T123004Z/ruby/.ext/common/psych.rb:271: warning: previous definition of load was here
...
```

This is caused by double requiring `ext/psych/lib/psych.rb` and its copy file `.ext/common/psych.rb`. 

A similar issue used to happen in fiddle. https://github.com/ruby/fiddle/issues/34

I'm monitoring the number of warnings during test, so this is a bit noisy.  Tentatively, I [committed the same fix](https://github.com/ruby/ruby/commit/a3cc9b3c8e8e55660e434015654dfc4e11e3a3ab) as fiddle directly into ruby master to make my monitoring easy. You can just import the fix if you like.  If not, please fix it in your way. (I'm not particular about how to fix.)

Thanks!

**Comment by tenderlove** [comment]
ah ya, that makes sense.  I'll pull the fix from fiddle in to psych.

**Comment by deivid-rodriguez** [comment]
I try to fix one redefinition warning and as a result, I create dozens of new instances of those :facepalm:. Thanks for fixing.

**Comment by tenderlove** [comment]
@deivid-rodriguez lol, no problem! Don't worry about it! 😆

**Comment by tenderlove** [comment]
I imported ruby/ruby@a3cc9b3c8e8e55660e434015654dfc4e11e3a3ab as 05d7e818a6abe3ee1c56b6be92f086647d73141c, so this should be fixed
