### ISSUE TITLE
possible to view comments when parsing yaml data

### ISSUE THREAD

**Issue by tansaku** [ruby/psych#464]
apologies if this is a ridiculous question, but I'm just wondering if it's possible to access the contents of comments when parsing YAML?

I know that comments are of course meant to be ignored, but I have a YAML file where there is some data in the comments that I'd like to transform and store - my fall back is just process the file separately but I wondered if there was an alternative.

**Comment by hsbt** [comment]
FYI: https://github.com/ruby/psych/issues/566
