### ISSUE TITLE
SnakeYAML update for syntax error fix

### ISSUE THREAD

**Issue by headius** [ruby/psych#477]
The issue reported in https://github.com/jruby/jruby/issues/6365 has now been fixed by SnakeYAML 1.28. I have updated psych master to SnakeYAML 1.28 and confirmed it fixes the issue. We now need a release of the psych gem.

We would like to include the fixed psych gem with this updated SnakeYAML in JRuby 9.2.15.0, due out tomorrow or Thursday, but users can update psych at any time if we can't meet that milestone

**Comment by headius** [comment]
Update commit is a88ff77f02bafafabfc6df9d159141bca2ae0217.

**Comment by tenderlove** [comment]
I shipped v3.3.1
