### ISSUE TITLE
JRuby tests failing

### ISSUE THREAD

**Issue by headius** [ruby/psych#479]
For about the past month the JRuby runs in CI have been failing:

https://github.com/ruby/psych/actions/workflows/ubuntu-jruby.yml

I have not looked into any of the failures but I suspect a couple things:

* No guard against running ractor tests, so they fail due to no ractor support
* Recent fixes to the C ext have not been translated to the JRuby ext

JRuby's branches for 9.2 and master are currently failing because we updated the psych gem and now its tests fail.

**Comment by headius** [comment]
I see now the most recent CI runs for JRuby don't even manage to run the tests. Something fails along the way in Bundler.

Here is a JRuby build showing the failures introduced recently:

https://travis-ci.com/github/jruby/jruby/jobs/486061152

**Comment by headius** [comment]
Note the ractor tests do not show up in the link above, but when I update JRuby's local copy of the psych tests (which includes the new ractor tests) they do attempt to run and fail with missing method errors.

**Comment by olleolleolle** [comment]
@headius 👋 Just a quick check, https://github.com/ruby/psych/actions/workflows/ubuntu-jruby.yml looks green, am I misinterpreting the hue of the indicators?

**Comment by hsbt** [comment]
The failing tests are skipped by #524.

We will remove them when resolving with JRuby.
