### ISSUE TITLE
`safe_load': wrong number of arguments (given 4, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by antenore** [ruby/psych#519]
I've reported this to [pdk](https://github.com/puppetlabs/pdk). There's some name clashing I guess, but I'm not sure where.

I just suppose the problem is more here (sorry if I'm wrong)

The original issue link: [`safe_load': wrong number of arguments (given 4, expected 1) (ArgumentError) · Issue #1143 · puppetlabs/pdk](https://github.com/puppetlabs/pdk/issues/1143) 

And the cut and paste:

> I've installed pdk as a gem, because I don't have better options at the moment.
> 
> When the gem psych is installed (v4.0.1) I have the above error, that sounds to me a weird name clashing.
> 
> I think the problem is in psych, I'll report the same to them, unfortunately I cannot investigate further, at the moment I've just removed psych.
> 
> The full error:
> 
>     $ pdk convert --noop --default-template -d
>     pdk (DEBUG): Detected a Puppet Module context at /puppet/modules/mail
>     pdk (DEBUG): Detected an unknown context at /puppet/dev/puppet/modules
>     Traceback (most recent call last):
>             20: from /home/antenore/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:22:in `<main>'
>             19: from /home/antenore/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:22:in `eval'
>             18: from /home/antenore/.rvm/gems/ruby-2.6.6/bin/pdk:23:in `<main>'
>             17: from /home/antenore/.rvm/gems/ruby-2.6.6/bin/pdk:23:in `load'
>             16: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/exe/pdk:6:in `<top (required)>'
>             15: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/lib/pdk/cli.rb:71:in `run'
>             14: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
>             13: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/cri-2.15.11/lib/cri/command.rb:298:in `run'
>             12: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/cri-2.15.11/lib/cri/command.rb:362:in `run_this'
>             11: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/lib/pdk/cli/convert.rb:37:in `block (2 levels) in <module:CLI>'
>             10: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/lib/pdk/cli/util.rb:300:in `analytics_screen_view'
>              9: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/lib/pdk.rb:67:in `analytics'
>              8: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/lib/pdk/config.rb:155:in `get_within_scopes'
>              7: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/lib/pdk/config.rb:155:in `each'
>              6: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/lib/pdk/config.rb:156:in `block in get_within_scopes'
>              5: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/lib/pdk/config.rb:297:in `traverse_object'
>              4: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/lib/pdk/config.rb:291:in `traverse_object'
>              3: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/lib/pdk/config/namespace.rb:99:in `[]'
>              2: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/lib/pdk/config/namespace.rb:345:in `settings'
>              1: from /home/antenore/.rvm/gems/ruby-2.6.6/gems/pdk-2.2.0/lib/pdk/config/yaml.rb:16:in `parse_file'
>     /home/antenore/.rvm/gems/ruby-2.6.6/gems/psych-4.0.1/lib/psych.rb:323:in `safe_load': wrong number of arguments (given 4, expected 1) (ArgumentError)

**Comment by olleolleolle** [comment]
I left a [comment](https://github.com/puppetlabs/pdk/issues/1143#issuecomment-919872943) in the other report, with an explanation. (This is not an issue in Psych.)

Hope this helps! 👋
