### ISSUE TITLE
Options to Psych.dump are undocumented

### ISSUE THREAD

**Issue by Phrogz** [ruby/psych#52]
http://stackoverflow.com/questions/9759302/documentation-for-psych-to-yaml-options

Are the functions in emitter.c the only options supported? Can documentation for these options be moved into the rb for `dump` so they're accessible? And then get any reasonably documented version described on ruby-doc.org?

**Comment by westlakem** [comment]
@tenderlove that is not appropriate documentation for "options" as it only shows the indentation... What other options are there?

**Comment by westlakem** [comment]
I'm really just looking for a way to output it with filled in variables (verbose if you will).  I have a lot of reused information in my auto-generated yaml file, and seeing *1, *2, *3 means I have to dig through the rest of the file to know what i'm looking at.

**Comment by andymeneely** [comment]
Where are the options documented? They don't have to be on ruby-doc.org, but I'd like to know where they are.

**Comment by dankohn** [comment]
See: https://stackoverflow.com/a/9759344/1935918

`.to_yaml(line_width: 80)` was particularly helpful for me.
