### ISSUE TITLE
Psych v4 is breaking bundle update

### ISSUE THREAD

**Issue by cooperka** [ruby/psych#531]
Routine `bundle update` fails with `ArgumentError: wrong number of arguments (given 4, expected 1)` after installing psych v4. See someone else's report at https://stackoverflow.com/questions/68899508/gem-install-wrong-number-of-arguments-given-4-expected-1 for more details.

I had a very similar issue upgrading other gems after psych v4 had been installed during a minor bundle update (I got it via a supbdepency of rdoc v6.4.0). My solution was to:
1. uninstall psych v4
2. manually require psych v3 in my Gemfile
3. run the bundle update again

This issue is happening on rails v5 + ruby v2.5 (trying to upgrade them both, but this issue prevented me from doing so for a while).

It's unclear to me what might be causing this, but I wanted to proactively share the issue report. Cheers.

**Comment by hsbt** [comment]
Ruby 2.5 and RubyGems 2.7 is not supported version of Pysch 4.

**Comment by cooperka** [comment]
Thanks @hsbt, that was unclear to me because it's not mentioned in any sort of docs or changelog that I can find. I'm guessing lots more people are struggling with this and not knowing why (especially as Rails 7 causes mandatory upgrades off of Rails 5). I understand you're probably as pressed for time as I am, but documentation can go a long way to helping everyone else in the community stay on the same page.

I'll report this to rdoc as well so they can constrain their version!

**Comment by deivid-rodriguez** [comment]
Recent RubyGems should support both psych 3 and psych 4, so running `gem update --system` should do the trick on Ruby 2.5 I believe.
