### ISSUE TITLE
Should we unbundle libyaml?

### ISSUE THREAD

**Issue by tenderlove** [ruby/psych#535]
We talked about unbundling libraries at the dev meeting, and I couldn't remember why we bundled libyaml.

I found the ticket [here](https://bugs.ruby-lang.org/issues/7375).  I guess the problem is that RubyGems depends on Psych, and Psych depends on libyaml, so we need to make sure you can install Psych so that you can install RubyGems.  Essentially you can't use RubyGems unless libyaml is installed.

If Ruby depends on RubyGems, and RubyGems depends on Psych, then Ruby depends on libyaml.

I don't like bundling libraries, but I don't think we should make a hard dependency on libyaml being installed.  In other words, I think we should continue to embed libyaml unless there is a different solution.

Any opinions? @hsbt @unak

**Comment by hsbt** [comment]
Is it related with libffi issue?

Basically, I agree with unbundle it. But We should confirm to build psych with libyaml package provided by vcpkg in mswin environment.

**Comment by boof** [comment]
Just a heads up because we stumbled upon this while having the libyaml-dev package install on Ubuntu LTS. When unbundled this will cause the whitespace issue (https://github.com/yaml/libyaml/pull/186) on Ubuntu LTS again since it still uses an old version w/o the fix.
