### ISSUE TITLE
release Psych 4.0.4?

### ISSUE THREAD

**Issue by sethboyles** [ruby/psych#561]
Hello,

We have been waiting a few months to be able to use the strict integer parsing flag contributed in January: https://github.com/ruby/psych/issues/273

Can we expect a new release of Psych anytime soon?  Is there anything we can do to help cut a new release?  

Thanks

**Comment by hsbt** [comment]
I  will handle this in the next week.

**Comment by hsbt** [comment]
done https://github.com/ruby/psych/releases/tag/v4.0.4
