### ISSUE TITLE
"0x_bae".to_yaml raises ArgumentError

### ISSUE THREAD

**Issue by payuramex** [ruby/psych#563]
Produces an 'ArgumentError: invalid value for Integer()

YAML version 3.1.0.

**Comment by 645383** [comment]
https://github.com/affogata/communit_360/pull/2242

**Comment by tisba** [comment]
Works fine with 4.0.3 (`YAML::VERSION`) on Ruby 3.1.2):

```
"0x_bae".to_yaml
 => "--- '0x_bae'\n"
```
