### ISSUE TITLE
"*.temp.mta.yaml" file is not a valid MTA descriptor: yaml: line 39: did not find expected key

### ISSUE THREAD

**Issue by InsafKhan30** [ruby/psych#582]
Hi,
I am facing issue during Fiori deployment of my app. While running the cmd "fiori add deploy-config cf" in VS Code it gives an error - 
the "C:\Users\abc\Appdata\Local\Temp\jkdnknd22883.temp.mta.yaml" file is not a valid MTA descriptor: yaml: line 39: did not find expected key.
i added indents to the MTA.yaml file but issue still remains. Sharing the content of my yaml here - 

![image](https://user-images.githubusercontent.com/73873463/192211226-ac191139-826d-4dad-97a2-d3120f1dfb06.png)

Regards,
Insaf

**Comment by olleolleolle** [comment]
@InsafKhan30 Hi! 👋 This message "file is not a valid MTA descriptor" is not emitted by Psych, but by other MTA-related tooling.

So, some other tool is telling us "the file does not have the right format".

I will close this Issue, now.

Hope this helps!
