### ISSUE TITLE
5.0 release breaks JRuby gem

### ISSUE THREAD

**Issue by dometto** [ruby/psych#598]
Seeing this error on GitHub actions and reproduced it on a clean `rvm` environment:

```
$ rvm use  jruby-9.4.0.0@psych-error --create
$ gem install psych
Fetching psych-5.0.0-java.gem
  jar dependencies for psych-5.0.0-java.gemspec . . .
Installing gem 'ruby-maven' . . .
Fetching ruby-maven-3.3.13.gem
Fetching ruby-maven-libs-3.3.9.gem
Successfully installed ruby-maven-libs-3.3.9
Successfully installed ruby-maven-3.3.13

[OMITTED MESSAGES ABOUT DOCUMENTATION]

using maven for the first time results in maven
downloading all its default plugin and can take time.
as those plugins get cached on disk and further execution
of maven is much faster then the first time.

      org.yaml:snakeyaml:1.33:compile
Successfully installed psych-5.0.0-java
Parsing documentation for psych-5.0.0-java
Installing ri documentation for psych-5.0.0-java
Done installing documentation for psych after 2 seconds
1 gem installed


$ irb
jruby-9.4.0.0 :001 > require 'psych'
 => true 
jruby-9.4.0.0 :002 > Psych.safe_load('--- foo') # => 'foo'
~/.rvm/gems/jruby-9.4.0.0@psych-error/gems/psych-5.0.0-java/lib/psych/parser.rb:62:in `parse': undefined method `_native_parse' for #<Psych::Parser:0x579ce2e9> (NoMethodError)     
```

**Comment by dometto** [comment]
@headius I see you've recently contributed a fix to the `_native_parse` method. Any idea why this might still be broken in the `gem` release (but apparently not on the `psych` CI)?

**Comment by headius** [comment]
I'll look into it today!

**Comment by headius** [comment]
I believe I have found the problem. It seems that the logic to load and bind the native parts of the Psych -java gem are incorrectly loading and binding the old version shipped within JRuby. I'm not sure if it is loading too early to be replaced, or if the loading logic is simply picking up the wrong gem.

**Comment by headius** [comment]
I was incorrect. I believe the 5.0 gem was released with an old psych.jar.

There's exactly one `parse` method in the sources on master. It takes ThreadContext and two IRubyObject arguments and has an annotation that binds it to `_native_parse`. The single-argument `parse` method was removed and the annotation added in 7b9d10c9dc2bb4dd71cb44f77d209a9f05f7def8 on Sep 19.

However the jar that ships with the 5.0 gem still has two `parse` methods:

```
$ javap -cp lib/ruby/gems/shared/gems/psych-5.0.0-java/lib/psych.jar org.jruby.ext.psych.PsychParser | grep parse
  public org.jruby.runtime.builtin.IRubyObject parse(org.jruby.runtime.ThreadContext, org.jruby.runtime.builtin.IRubyObject);
  public org.jruby.runtime.builtin.IRubyObject parse(org.jruby.runtime.ThreadContext, org.jruby.runtime.builtin.IRubyObject, org.jruby.runtime.builtin.IRubyObject);
```

And when stepping through the init process, I can see those methods do not have the `_native_parse` name attached to them.

@hsbt @nobu We need to do a clean build of the JRuby ext and release a 5.0.1 to fix this.

**Comment by hsbt** [comment]
oops. I will handle this today.

**Comment by headius** [comment]
5.0.1 does appear to pass the example @dometto provided!

**Comment by dometto** [comment]
Thanks all for the fast reply and fix!

**Comment by hsbt** [comment]
Your report is also really helpful for the final release of Ruby 3.2. Thanks all.
