### ISSUE TITLE
macOS - will psych.bundle load?

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/psych#599]
Confused by this line in psych.rb
https://github.com/ruby/psych/blob/bdf20e604204024eae580fbd5f697e171e55ac2d/lib/psych.rb#L13

Will that load the extension on macOS?  Can't test locally.  Maybe the below, which should be equivalent to the correct filename (`psych.bundle` for macOS) :

```ruby
require "psych.#{RbConfig::CONFIG['DLEXT']}"
```
I see there is no error handling, so `require` parses the filename extension?

**Comment by hsbt** [comment]
Ruby will fallback `.so` extension to `.bundle` in macOS.
